name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install php
        run: php -v
      
      - name: Run php Builtin Server
        run: php -S 0.0.0.0:58800 .
